name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Azure CLI
    - name: Set up Azure CLI
      uses: azure/setup-azurecli@v1
      with:
        azure-cli-version: '2.0.81'

    # Step 3: Log in to Azure using the Service Principal
    - name: Login to Azure
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    # Step 4: Set the Azure subscription
    - name: Set Azure subscription
      run: |
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Step 5: Deploy to Azure Web App
    - name: Deploy to Azure Web App
      run: |
        az webapp up --name ${{ secrets.AZURE_WEB_APP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --sku B1 --runtime "NODE|14-lts" --plan ${{ secrets.AZURE_APP_SERVICE_PLAN }}

